# Generated by Django 3.1.5 on 2021-01-11 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main_currency', to='currency.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_currency', to='currency.currency'),
        ),
    ]
