# Generated by Django 3.1.5 on 2021-01-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='from_wallet',
        ),
    ]
