# Generated by Django 3.1.5 on 2021-01-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_remove_fund_from_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
