# Generated by Django 3.1.5 on 2021-01-13 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_auto_20210112_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='to_wallet',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='from_wallet',
        ),
        migrations.AddField(
            model_name='fund',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fund_owner', to='currency.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_owner', to='currency.customuser'),
            preserve_default=False,
        ),
    ]
