# Generated by Django 3.1.5 on 2021-01-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_auto_20210113_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='user',
            new_name='to_user',
        ),
        migrations.RenameField(
            model_name='withdrawal',
            old_name='user',
            new_name='from_user',
        ),
    ]
